main:
   - name: Home
     pageRef: /
     weight: 1
   - name: Blog
     pageRef: series
     weight: 2
   - name: Tag
     pageRef: tags
     weight: 3
footer:
   - pre: github
     name: GitHub
     url: https://github.com/togally
     weight: 1